"""
Prometheus metrics for HomeSight AI Sidecar

Tracks:
- API request counts and latency
- LLM inference time and token usage
- RAG retrieval performance
- Document ingestion metrics
- Active sessions
"""

from prometheus_client import Counter, Histogram, Gauge, generate_latest
from functools import wraps
import time
import logging

logger = logging.getLogger(__name__)

# ============================================================================
# REQUEST METRICS
# ============================================================================

# API request counter (by endpoint and status)
api_requests = Counter(
    'ai_sidecar_api_requests_total',
    'Total API requests to AI Sidecar',
    ['endpoint', 'method', 'status']
)

# API request latency histogram (in seconds)
api_request_duration = Histogram(
    'ai_sidecar_api_request_duration_seconds',
    'AI Sidecar API request duration in seconds',
    ['endpoint', 'method'],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0)
)

# ============================================================================
# LLM METRICS
# ============================================================================

# LLM inference time (in seconds)
llm_inference_duration = Histogram(
    'ai_sidecar_llm_inference_duration_seconds',
    'LLM inference duration in seconds',
    ['model', 'provider'],  # e.g., model='llama-3.2-3b', provider='local'
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0)
)

# LLM inference counter (by model and provider)
llm_inferences = Counter(
    'ai_sidecar_llm_inferences_total',
    'Total LLM inference calls',
    ['model', 'provider', 'status']  # status: success, error, timeout
)

# LLM token usage (input tokens)
llm_input_tokens = Counter(
    'ai_sidecar_llm_input_tokens_total',
    'Total input tokens sent to LLM',
    ['model', 'provider']
)

# LLM token usage (output tokens)
llm_output_tokens = Counter(
    'ai_sidecar_llm_output_tokens_total',
    'Total output tokens generated by LLM',
    ['model', 'provider']
)

# ============================================================================
# RAG METRICS
# ============================================================================

# RAG retrieval latency (in seconds)
rag_retrieval_duration = Histogram(
    'ai_sidecar_rag_retrieval_duration_seconds',
    'RAG document retrieval duration in seconds',
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 5.0)
)

# RAG retrieval counter
rag_retrievals = Counter(
    'ai_sidecar_rag_retrievals_total',
    'Total RAG document retrievals',
    ['status']  # status: success, empty, error
)

# Number of documents in RAG database
rag_documents = Gauge(
    'ai_sidecar_rag_documents_total',
    'Total documents in RAG database'
)

# ============================================================================
# CHAT METRICS
# ============================================================================

# Chat request counter (by status)
chat_requests = Counter(
    'ai_sidecar_chat_requests_total',
    'Total chat requests',
    ['status']  # status: success, error, validation_error
)

# Chat response time (in seconds)
chat_response_time = Histogram(
    'ai_sidecar_chat_response_time_seconds',
    'Chat response generation time in seconds',
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0)
)

# Number of actions executed in chat
chat_actions = Counter(
    'ai_sidecar_chat_actions_total',
    'Total actions executed from chat',
    ['action_type', 'status']  # e.g., action_type='reset_device', status='success'
)

# ============================================================================
# ANALYSIS METRICS
# ============================================================================

# Analysis request counter
analysis_requests = Counter(
    'ai_sidecar_analysis_requests_total',
    'Total analysis requests',
    ['status']  # status: queued, processing, success, error
)

# Analysis time (in seconds)
analysis_time = Histogram(
    'ai_sidecar_analysis_time_seconds',
    'Time to complete analysis in seconds',
    buckets=(0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0)
)

# Analysis queue size
analysis_queue_size = Gauge(
    'ai_sidecar_analysis_queue_size',
    'Current size of analysis queue'
)

# ============================================================================
# SESSION METRICS
# ============================================================================

# Active sessions gauge
active_sessions = Gauge(
    'ai_sidecar_active_sessions',
    'Number of active chat sessions'
)

# Total sessions created counter
sessions_created = Counter(
    'ai_sidecar_sessions_created_total',
    'Total chat sessions created'
)

# ============================================================================
# DOCUMENT INGESTION METRICS
# ============================================================================

# Documents ingested counter
documents_ingested = Counter(
    'ai_sidecar_documents_ingested_total',
    'Total documents ingested into RAG',
    ['source_type', 'status']  # e.g., source_type='manual', status='success'
)

# Document ingestion time (in seconds)
document_ingestion_time = Histogram(
    'ai_sidecar_document_ingestion_time_seconds',
    'Time to ingest a document in seconds',
    ['source_type'],
    buckets=(0.1, 0.5, 1.0, 5.0, 10.0, 30.0)
)

# ============================================================================
# KNOWLEDGE BASE INGESTION METRICS
# ============================================================================

# Knowledge base ingestion counter (by device ingestion status)
kb_ingestions = Counter(
    'ai_sidecar_kb_ingestions_total',
    'Total knowledge base ingestions by status',
    ['status']  # status: success, failed, partial
)

# Knowledge base confidence gauge (average confidence score)
kb_average_confidence = Gauge(
    'ai_sidecar_kb_average_confidence',
    'Average confidence score of ingested knowledge bases'
)

# Knowledge base sources counter (by source type)
kb_sources = Counter(
    'ai_sidecar_kb_sources_total',
    'Total knowledge sources used in ingestions',
    ['source_type']  # e.g., source_type='official_pdf', 'ai_generated'
)

# ============================================================================
# MIDDLEWARE FOR AUTOMATIC METRIC COLLECTION
# ============================================================================

def track_request_metrics(endpoint: str, method: str):
    """Decorator to automatically track API request metrics"""
    def decorator(func):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            start_time = time.time()
            status = "error"
            try:
                result = await func(*args, **kwargs)
                status = "success"
                return result
            except Exception as e:
                status = "error"
                raise
            finally:
                duration = time.time() - start_time
                api_request_duration.labels(endpoint=endpoint, method=method).observe(duration)
                api_requests.labels(endpoint=endpoint, method=method, status=status).inc()

        @wraps(func)
        def sync_wrapper(*args, **kwargs):
            start_time = time.time()
            status = "error"
            try:
                result = func(*args, **kwargs)
                status = "success"
                return result
            except Exception as e:
                status = "error"
                raise
            finally:
                duration = time.time() - start_time
                api_request_duration.labels(endpoint=endpoint, method=method).observe(duration)
                api_requests.labels(endpoint=endpoint, method=method, status=status).inc()

        # Return appropriate wrapper based on function type
        if asyncio.iscoroutinefunction(func):
            return async_wrapper
        else:
            return sync_wrapper

    return decorator


import asyncio


def get_metrics():
    """Return Prometheus metrics in text format"""
    return generate_latest()
